package cat.ogasoft.protocolizer.exceptions;

/**
 *
 * @author Oscar Galera i Alfaro
 * @date   Mar 19, 2017 [3:16:59 PM]
 * 
 * @brief Exception generated by the processor when something goes wrong :S
 */
public class ProcessException extends Exception{

    public ProcessException(String message) {
        super(message);
    }
    
    public ProcessException(String message, Throwable cause) {
        super(message, cause);
    }
    
}
