// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prova7.proto

package cat.ogasoft.protocolizer.messages;

public final class prova7 {
  private prova7() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:C1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    boolean hasAaa();
    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova6.M1 getAaa();
    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder getAaaOrBuilder();

    /**
     * <code>required int32 a = 2;</code>
     */
    boolean hasA();
    /**
     * <code>required int32 a = 2;</code>
     */
    int getA();
  }
  /**
   * Protobuf type {@code C1}
   */
  public  static final class C1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C1)
      C1OrBuilder {
    // Use C1.newBuilder() to construct.
    private C1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C1() {
      a_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cat.ogasoft.protocolizer.messages.prova6.M1.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = aaa_.toBuilder();
              }
              aaa_ = input.readMessage(cat.ogasoft.protocolizer.messages.prova6.M1.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(aaa_);
                aaa_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              a_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.prova7.internal_static_C1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.prova7.internal_static_C1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.prova7.C1.class, cat.ogasoft.protocolizer.messages.prova7.C1.Builder.class);
    }

    private int bitField0_;
    public static final int AAA_FIELD_NUMBER = 1;
    private cat.ogasoft.protocolizer.messages.prova6.M1 aaa_;
    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    public boolean hasAaa() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova6.M1 getAaa() {
      return aaa_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance() : aaa_;
    }
    /**
     * <code>optional .M1 aaa = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder getAaaOrBuilder() {
      return aaa_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance() : aaa_;
    }

    public static final int A_FIELD_NUMBER = 2;
    private int a_;
    /**
     * <code>required int32 a = 2;</code>
     */
    public boolean hasA() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 a = 2;</code>
     */
    public int getA() {
      return a_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAaa()) {
        if (!getAaa().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getAaa());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, a_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAaa());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, a_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova7.C1)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.prova7.C1 other = (cat.ogasoft.protocolizer.messages.prova7.C1) obj;

      boolean result = true;
      result = result && (hasAaa() == other.hasAaa());
      if (hasAaa()) {
        result = result && getAaa()
            .equals(other.getAaa());
      }
      result = result && (hasA() == other.hasA());
      if (hasA()) {
        result = result && (getA()
            == other.getA());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAaa()) {
        hash = (37 * hash) + AAA_FIELD_NUMBER;
        hash = (53 * hash) + getAaa().hashCode();
      }
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova7.C1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova7.C1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C1)
        cat.ogasoft.protocolizer.messages.prova7.C1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova7.internal_static_C1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova7.internal_static_C1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova7.C1.class, cat.ogasoft.protocolizer.messages.prova7.C1.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.prova7.C1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAaaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (aaaBuilder_ == null) {
          aaa_ = null;
        } else {
          aaaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.prova7.internal_static_C1_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.prova7.C1 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.prova7.C1.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.prova7.C1 build() {
        cat.ogasoft.protocolizer.messages.prova7.C1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.prova7.C1 buildPartial() {
        cat.ogasoft.protocolizer.messages.prova7.C1 result = new cat.ogasoft.protocolizer.messages.prova7.C1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (aaaBuilder_ == null) {
          result.aaa_ = aaa_;
        } else {
          result.aaa_ = aaaBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.a_ = a_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.prova7.C1) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.prova7.C1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova7.C1 other) {
        if (other == cat.ogasoft.protocolizer.messages.prova7.C1.getDefaultInstance()) return this;
        if (other.hasAaa()) {
          mergeAaa(other.getAaa());
        }
        if (other.hasA()) {
          setA(other.getA());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasA()) {
          return false;
        }
        if (hasAaa()) {
          if (!getAaa().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.prova7.C1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.prova7.C1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private cat.ogasoft.protocolizer.messages.prova6.M1 aaa_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova6.M1, cat.ogasoft.protocolizer.messages.prova6.M1.Builder, cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder> aaaBuilder_;
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public boolean hasAaa() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1 getAaa() {
        if (aaaBuilder_ == null) {
          return aaa_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance() : aaa_;
        } else {
          return aaaBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public Builder setAaa(cat.ogasoft.protocolizer.messages.prova6.M1 value) {
        if (aaaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          aaa_ = value;
          onChanged();
        } else {
          aaaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public Builder setAaa(
          cat.ogasoft.protocolizer.messages.prova6.M1.Builder builderForValue) {
        if (aaaBuilder_ == null) {
          aaa_ = builderForValue.build();
          onChanged();
        } else {
          aaaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public Builder mergeAaa(cat.ogasoft.protocolizer.messages.prova6.M1 value) {
        if (aaaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              aaa_ != null &&
              aaa_ != cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance()) {
            aaa_ =
              cat.ogasoft.protocolizer.messages.prova6.M1.newBuilder(aaa_).mergeFrom(value).buildPartial();
          } else {
            aaa_ = value;
          }
          onChanged();
        } else {
          aaaBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public Builder clearAaa() {
        if (aaaBuilder_ == null) {
          aaa_ = null;
          onChanged();
        } else {
          aaaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1.Builder getAaaBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAaaFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder getAaaOrBuilder() {
        if (aaaBuilder_ != null) {
          return aaaBuilder_.getMessageOrBuilder();
        } else {
          return aaa_ == null ?
              cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance() : aaa_;
        }
      }
      /**
       * <code>optional .M1 aaa = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova6.M1, cat.ogasoft.protocolizer.messages.prova6.M1.Builder, cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder> 
          getAaaFieldBuilder() {
        if (aaaBuilder_ == null) {
          aaaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.prova6.M1, cat.ogasoft.protocolizer.messages.prova6.M1.Builder, cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder>(
                  getAaa(),
                  getParentForChildren(),
                  isClean());
          aaa_ = null;
        }
        return aaaBuilder_;
      }

      private int a_ ;
      /**
       * <code>required int32 a = 2;</code>
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 a = 2;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>required int32 a = 2;</code>
       */
      public Builder setA(int value) {
        bitField0_ |= 0x00000002;
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 a = 2;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000002);
        a_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C1)
    }

    // @@protoc_insertion_point(class_scope:C1)
    private static final cat.ogasoft.protocolizer.messages.prova7.C1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova7.C1();
    }

    public static cat.ogasoft.protocolizer.messages.prova7.C1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C1>
        PARSER = new com.google.protobuf.AbstractParser<C1>() {
      public C1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C1> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.prova7.C1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014prova7.proto\032\014prova6.proto\"!\n\002C1\022\020\n\003aa" +
      "a\030\001 \001(\0132\003.M1\022\t\n\001a\030\002 \002(\005B+\n!cat.ogasoft.p" +
      "rotocolizer.messagesB\006prova7"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cat.ogasoft.protocolizer.messages.prova6.getDescriptor(),
        }, assigner);
    internal_static_C1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C1_descriptor,
        new java.lang.String[] { "Aaa", "A", });
    cat.ogasoft.protocolizer.messages.prova6.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
