// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provaaa.proto

package cat.ogasoft.protocolizer.messages;

public final class provaaa {
  private provaaa() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface M1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional int32 m3 = 1;</code>
     */
    boolean hasM3();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional int32 m3 = 1;</code>
     */
    int getM3();
  }
  /**
   * Protobuf type {@code M1}
   */
  public  static final class M1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M1)
      M1OrBuilder {
    // Use M1.newBuilder() to construct.
    private M1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M1() {
      m3_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              m3_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.provaaa.M1.class, cat.ogasoft.protocolizer.messages.provaaa.M1.Builder.class);
    }

    private int bitField0_;
    public static final int M3_FIELD_NUMBER = 1;
    private int m3_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional int32 m3 = 1;</code>
     */
    public boolean hasM3() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional int32 m3 = 1;</code>
     */
    public int getM3() {
      return m3_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, m3_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, m3_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.provaaa.M1)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.provaaa.M1 other = (cat.ogasoft.protocolizer.messages.provaaa.M1) obj;

      boolean result = true;
      result = result && (hasM3() == other.hasM3());
      if (hasM3()) {
        result = result && (getM3()
            == other.getM3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM3()) {
        hash = (37 * hash) + M3_FIELD_NUMBER;
        hash = (53 * hash) + getM3();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.provaaa.M1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M1)
        cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.provaaa.M1.class, cat.ogasoft.protocolizer.messages.provaaa.M1.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.provaaa.M1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        m3_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M1_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M1 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M1 build() {
        cat.ogasoft.protocolizer.messages.provaaa.M1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M1 buildPartial() {
        cat.ogasoft.protocolizer.messages.provaaa.M1 result = new cat.ogasoft.protocolizer.messages.provaaa.M1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.m3_ = m3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.provaaa.M1) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.provaaa.M1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.provaaa.M1 other) {
        if (other == cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance()) return this;
        if (other.hasM3()) {
          setM3(other.getM3());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.provaaa.M1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.provaaa.M1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int m3_ ;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional int32 m3 = 1;</code>
       */
      public boolean hasM3() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional int32 m3 = 1;</code>
       */
      public int getM3() {
        return m3_;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional int32 m3 = 1;</code>
       */
      public Builder setM3(int value) {
        bitField0_ |= 0x00000001;
        m3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional int32 m3 = 1;</code>
       */
      public Builder clearM3() {
        bitField0_ = (bitField0_ & ~0x00000001);
        m3_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M1)
    }

    // @@protoc_insertion_point(class_scope:M1)
    private static final cat.ogasoft.protocolizer.messages.provaaa.M1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.provaaa.M1();
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M1>
        PARSER = new com.google.protobuf.AbstractParser<M1>() {
      public M1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M1> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.provaaa.M1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface M3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    boolean hasCaca();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    int getCaca();

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    boolean hasProva();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M2 getProva();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder getProvaOrBuilder();
  }
  /**
   * Protobuf type {@code M3}
   */
  public  static final class M3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M3)
      M3OrBuilder {
    // Use M3.newBuilder() to construct.
    private M3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M3() {
      caca_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              caca_ = input.readInt32();
              break;
            }
            case 18: {
              cat.ogasoft.protocolizer.messages.provaaa.M2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = prova_.toBuilder();
              }
              prova_ = input.readMessage(cat.ogasoft.protocolizer.messages.provaaa.M2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prova_);
                prova_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.provaaa.M3.class, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder.class);
    }

    private int bitField0_;
    public static final int CACA_FIELD_NUMBER = 1;
    private int caca_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    public boolean hasCaca() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    public int getCaca() {
      return caca_;
    }

    public static final int PROVA_FIELD_NUMBER = 2;
    private cat.ogasoft.protocolizer.messages.provaaa.M2 prova_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    public boolean hasProva() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M2 getProva() {
      return prova_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance() : prova_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M2 prova = 2;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder getProvaOrBuilder() {
      return prova_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance() : prova_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCaca()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProva()) {
        if (!getProva().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, caca_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getProva());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, caca_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProva());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.provaaa.M3)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.provaaa.M3 other = (cat.ogasoft.protocolizer.messages.provaaa.M3) obj;

      boolean result = true;
      result = result && (hasCaca() == other.hasCaca());
      if (hasCaca()) {
        result = result && (getCaca()
            == other.getCaca());
      }
      result = result && (hasProva() == other.hasProva());
      if (hasProva()) {
        result = result && getProva()
            .equals(other.getProva());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCaca()) {
        hash = (37 * hash) + CACA_FIELD_NUMBER;
        hash = (53 * hash) + getCaca();
      }
      if (hasProva()) {
        hash = (37 * hash) + PROVA_FIELD_NUMBER;
        hash = (53 * hash) + getProva().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.provaaa.M3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M3)
        cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.provaaa.M3.class, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.provaaa.M3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProvaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        caca_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (provaBuilder_ == null) {
          prova_ = null;
        } else {
          provaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M3_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M3 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M3 build() {
        cat.ogasoft.protocolizer.messages.provaaa.M3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M3 buildPartial() {
        cat.ogasoft.protocolizer.messages.provaaa.M3 result = new cat.ogasoft.protocolizer.messages.provaaa.M3(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.caca_ = caca_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (provaBuilder_ == null) {
          result.prova_ = prova_;
        } else {
          result.prova_ = provaBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.provaaa.M3) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.provaaa.M3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.provaaa.M3 other) {
        if (other == cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance()) return this;
        if (other.hasCaca()) {
          setCaca(other.getCaca());
        }
        if (other.hasProva()) {
          mergeProva(other.getProva());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCaca()) {
          return false;
        }
        if (hasProva()) {
          if (!getProva().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.provaaa.M3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.provaaa.M3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int caca_ ;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public boolean hasCaca() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public int getCaca() {
        return caca_;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public Builder setCaca(int value) {
        bitField0_ |= 0x00000001;
        caca_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public Builder clearCaca() {
        bitField0_ = (bitField0_ & ~0x00000001);
        caca_ = 0;
        onChanged();
        return this;
      }

      private cat.ogasoft.protocolizer.messages.provaaa.M2 prova_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M2, cat.ogasoft.protocolizer.messages.provaaa.M2.Builder, cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder> provaBuilder_;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public boolean hasProva() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M2 getProva() {
        if (provaBuilder_ == null) {
          return prova_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance() : prova_;
        } else {
          return provaBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public Builder setProva(cat.ogasoft.protocolizer.messages.provaaa.M2 value) {
        if (provaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prova_ = value;
          onChanged();
        } else {
          provaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public Builder setProva(
          cat.ogasoft.protocolizer.messages.provaaa.M2.Builder builderForValue) {
        if (provaBuilder_ == null) {
          prova_ = builderForValue.build();
          onChanged();
        } else {
          provaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public Builder mergeProva(cat.ogasoft.protocolizer.messages.provaaa.M2 value) {
        if (provaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              prova_ != null &&
              prova_ != cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance()) {
            prova_ =
              cat.ogasoft.protocolizer.messages.provaaa.M2.newBuilder(prova_).mergeFrom(value).buildPartial();
          } else {
            prova_ = value;
          }
          onChanged();
        } else {
          provaBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public Builder clearProva() {
        if (provaBuilder_ == null) {
          prova_ = null;
          onChanged();
        } else {
          provaBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M2.Builder getProvaBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProvaFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder getProvaOrBuilder() {
        if (provaBuilder_ != null) {
          return provaBuilder_.getMessageOrBuilder();
        } else {
          return prova_ == null ?
              cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance() : prova_;
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M2 prova = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M2, cat.ogasoft.protocolizer.messages.provaaa.M2.Builder, cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder> 
          getProvaFieldBuilder() {
        if (provaBuilder_ == null) {
          provaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.provaaa.M2, cat.ogasoft.protocolizer.messages.provaaa.M2.Builder, cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder>(
                  getProva(),
                  getParentForChildren(),
                  isClean());
          prova_ = null;
        }
        return provaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M3)
    }

    // @@protoc_insertion_point(class_scope:M3)
    private static final cat.ogasoft.protocolizer.messages.provaaa.M3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.provaaa.M3();
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M3>
        PARSER = new com.google.protobuf.AbstractParser<M3>() {
      public M3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M3> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.provaaa.M3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface M2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    boolean hasM1();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M1 getM1();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder getM1OrBuilder();

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    boolean hasM3();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M3 getM3();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getM3OrBuilder();

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    boolean hasOk();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M3 getOk();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getOkOrBuilder();
  }
  /**
   * Protobuf type {@code M2}
   */
  public  static final class M2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M2)
      M2OrBuilder {
    // Use M2.newBuilder() to construct.
    private M2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M2() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cat.ogasoft.protocolizer.messages.provaaa.M1.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = m1_.toBuilder();
              }
              m1_ = input.readMessage(cat.ogasoft.protocolizer.messages.provaaa.M1.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m1_);
                m1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              cat.ogasoft.protocolizer.messages.provaaa.M3.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = m3_.toBuilder();
              }
              m3_ = input.readMessage(cat.ogasoft.protocolizer.messages.provaaa.M3.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m3_);
                m3_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              cat.ogasoft.protocolizer.messages.provaaa.M3.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = ok_.toBuilder();
              }
              ok_ = input.readMessage(cat.ogasoft.protocolizer.messages.provaaa.M3.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ok_);
                ok_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.provaaa.M2.class, cat.ogasoft.protocolizer.messages.provaaa.M2.Builder.class);
    }

    private int bitField0_;
    public static final int M1_FIELD_NUMBER = 1;
    private cat.ogasoft.protocolizer.messages.provaaa.M1 m1_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    public boolean hasM1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M1 getM1() {
      return m1_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance() : m1_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1 m1 = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder getM1OrBuilder() {
      return m1_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance() : m1_;
    }

    public static final int M3_FIELD_NUMBER = 2;
    private cat.ogasoft.protocolizer.messages.provaaa.M3 m3_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    public boolean hasM3() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M3 getM3() {
      return m3_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : m3_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 m3 = 2;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getM3OrBuilder() {
      return m3_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : m3_;
    }

    public static final int OK_FIELD_NUMBER = 3;
    private cat.ogasoft.protocolizer.messages.provaaa.M3 ok_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M3 getOk() {
      return ok_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : ok_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M3 ok = 3;</code>
     */
    public cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getOkOrBuilder() {
      return ok_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : ok_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasM3()) {
        if (!getM3().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasOk()) {
        if (!getOk().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getM1());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getM3());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getOk());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getM1());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getM3());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOk());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.provaaa.M2)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.provaaa.M2 other = (cat.ogasoft.protocolizer.messages.provaaa.M2) obj;

      boolean result = true;
      result = result && (hasM1() == other.hasM1());
      if (hasM1()) {
        result = result && getM1()
            .equals(other.getM1());
      }
      result = result && (hasM3() == other.hasM3());
      if (hasM3()) {
        result = result && getM3()
            .equals(other.getM3());
      }
      result = result && (hasOk() == other.hasOk());
      if (hasOk()) {
        result = result && getOk()
            .equals(other.getOk());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM1()) {
        hash = (37 * hash) + M1_FIELD_NUMBER;
        hash = (53 * hash) + getM1().hashCode();
      }
      if (hasM3()) {
        hash = (37 * hash) + M3_FIELD_NUMBER;
        hash = (53 * hash) + getM3().hashCode();
      }
      if (hasOk()) {
        hash = (37 * hash) + OK_FIELD_NUMBER;
        hash = (53 * hash) + getOk().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.provaaa.M2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.provaaa.M2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M2)
        cat.ogasoft.protocolizer.messages.provaaa.M2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.provaaa.M2.class, cat.ogasoft.protocolizer.messages.provaaa.M2.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.provaaa.M2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getM1FieldBuilder();
          getM3FieldBuilder();
          getOkFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (m1Builder_ == null) {
          m1_ = null;
        } else {
          m1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (m3Builder_ == null) {
          m3_ = null;
        } else {
          m3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (okBuilder_ == null) {
          ok_ = null;
        } else {
          okBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.internal_static_M2_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M2 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M2 build() {
        cat.ogasoft.protocolizer.messages.provaaa.M2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.provaaa.M2 buildPartial() {
        cat.ogasoft.protocolizer.messages.provaaa.M2 result = new cat.ogasoft.protocolizer.messages.provaaa.M2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (m1Builder_ == null) {
          result.m1_ = m1_;
        } else {
          result.m1_ = m1Builder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (m3Builder_ == null) {
          result.m3_ = m3_;
        } else {
          result.m3_ = m3Builder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (okBuilder_ == null) {
          result.ok_ = ok_;
        } else {
          result.ok_ = okBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.provaaa.M2) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.provaaa.M2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.provaaa.M2 other) {
        if (other == cat.ogasoft.protocolizer.messages.provaaa.M2.getDefaultInstance()) return this;
        if (other.hasM1()) {
          mergeM1(other.getM1());
        }
        if (other.hasM3()) {
          mergeM3(other.getM3());
        }
        if (other.hasOk()) {
          mergeOk(other.getOk());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasM3()) {
          if (!getM3().isInitialized()) {
            return false;
          }
        }
        if (hasOk()) {
          if (!getOk().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.provaaa.M2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.provaaa.M2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private cat.ogasoft.protocolizer.messages.provaaa.M1 m1_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M1, cat.ogasoft.protocolizer.messages.provaaa.M1.Builder, cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder> m1Builder_;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public boolean hasM1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M1 getM1() {
        if (m1Builder_ == null) {
          return m1_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance() : m1_;
        } else {
          return m1Builder_.getMessage();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public Builder setM1(cat.ogasoft.protocolizer.messages.provaaa.M1 value) {
        if (m1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m1_ = value;
          onChanged();
        } else {
          m1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public Builder setM1(
          cat.ogasoft.protocolizer.messages.provaaa.M1.Builder builderForValue) {
        if (m1Builder_ == null) {
          m1_ = builderForValue.build();
          onChanged();
        } else {
          m1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public Builder mergeM1(cat.ogasoft.protocolizer.messages.provaaa.M1 value) {
        if (m1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              m1_ != null &&
              m1_ != cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance()) {
            m1_ =
              cat.ogasoft.protocolizer.messages.provaaa.M1.newBuilder(m1_).mergeFrom(value).buildPartial();
          } else {
            m1_ = value;
          }
          onChanged();
        } else {
          m1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public Builder clearM1() {
        if (m1Builder_ == null) {
          m1_ = null;
          onChanged();
        } else {
          m1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M1.Builder getM1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getM1FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder getM1OrBuilder() {
        if (m1Builder_ != null) {
          return m1Builder_.getMessageOrBuilder();
        } else {
          return m1_ == null ?
              cat.ogasoft.protocolizer.messages.provaaa.M1.getDefaultInstance() : m1_;
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1 m1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M1, cat.ogasoft.protocolizer.messages.provaaa.M1.Builder, cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder> 
          getM1FieldBuilder() {
        if (m1Builder_ == null) {
          m1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.provaaa.M1, cat.ogasoft.protocolizer.messages.provaaa.M1.Builder, cat.ogasoft.protocolizer.messages.provaaa.M1OrBuilder>(
                  getM1(),
                  getParentForChildren(),
                  isClean());
          m1_ = null;
        }
        return m1Builder_;
      }

      private cat.ogasoft.protocolizer.messages.provaaa.M3 m3_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder> m3Builder_;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public boolean hasM3() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3 getM3() {
        if (m3Builder_ == null) {
          return m3_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : m3_;
        } else {
          return m3Builder_.getMessage();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public Builder setM3(cat.ogasoft.protocolizer.messages.provaaa.M3 value) {
        if (m3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m3_ = value;
          onChanged();
        } else {
          m3Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public Builder setM3(
          cat.ogasoft.protocolizer.messages.provaaa.M3.Builder builderForValue) {
        if (m3Builder_ == null) {
          m3_ = builderForValue.build();
          onChanged();
        } else {
          m3Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public Builder mergeM3(cat.ogasoft.protocolizer.messages.provaaa.M3 value) {
        if (m3Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              m3_ != null &&
              m3_ != cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance()) {
            m3_ =
              cat.ogasoft.protocolizer.messages.provaaa.M3.newBuilder(m3_).mergeFrom(value).buildPartial();
          } else {
            m3_ = value;
          }
          onChanged();
        } else {
          m3Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public Builder clearM3() {
        if (m3Builder_ == null) {
          m3_ = null;
          onChanged();
        } else {
          m3Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3.Builder getM3Builder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getM3FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getM3OrBuilder() {
        if (m3Builder_ != null) {
          return m3Builder_.getMessageOrBuilder();
        } else {
          return m3_ == null ?
              cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : m3_;
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 m3 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder> 
          getM3FieldBuilder() {
        if (m3Builder_ == null) {
          m3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder>(
                  getM3(),
                  getParentForChildren(),
                  isClean());
          m3_ = null;
        }
        return m3Builder_;
      }

      private cat.ogasoft.protocolizer.messages.provaaa.M3 ok_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder> okBuilder_;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3 getOk() {
        if (okBuilder_ == null) {
          return ok_ == null ? cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : ok_;
        } else {
          return okBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public Builder setOk(cat.ogasoft.protocolizer.messages.provaaa.M3 value) {
        if (okBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ok_ = value;
          onChanged();
        } else {
          okBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public Builder setOk(
          cat.ogasoft.protocolizer.messages.provaaa.M3.Builder builderForValue) {
        if (okBuilder_ == null) {
          ok_ = builderForValue.build();
          onChanged();
        } else {
          okBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public Builder mergeOk(cat.ogasoft.protocolizer.messages.provaaa.M3 value) {
        if (okBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              ok_ != null &&
              ok_ != cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance()) {
            ok_ =
              cat.ogasoft.protocolizer.messages.provaaa.M3.newBuilder(ok_).mergeFrom(value).buildPartial();
          } else {
            ok_ = value;
          }
          onChanged();
        } else {
          okBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public Builder clearOk() {
        if (okBuilder_ == null) {
          ok_ = null;
          onChanged();
        } else {
          okBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3.Builder getOkBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getOkFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      public cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder getOkOrBuilder() {
        if (okBuilder_ != null) {
          return okBuilder_.getMessageOrBuilder();
        } else {
          return ok_ == null ?
              cat.ogasoft.protocolizer.messages.provaaa.M3.getDefaultInstance() : ok_;
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M3 ok = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder> 
          getOkFieldBuilder() {
        if (okBuilder_ == null) {
          okBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.provaaa.M3, cat.ogasoft.protocolizer.messages.provaaa.M3.Builder, cat.ogasoft.protocolizer.messages.provaaa.M3OrBuilder>(
                  getOk(),
                  getParentForChildren(),
                  isClean());
          ok_ = null;
        }
        return okBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M2)
    }

    // @@protoc_insertion_point(class_scope:M2)
    private static final cat.ogasoft.protocolizer.messages.provaaa.M2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.provaaa.M2();
    }

    public static cat.ogasoft.protocolizer.messages.provaaa.M2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M2>
        PARSER = new com.google.protobuf.AbstractParser<M2>() {
      public M2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M2> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.provaaa.M2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M3_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprovaaa.proto\"\020\n\002M1\022\n\n\002m3\030\001 \001(\005\"&\n\002M3\022" +
      "\014\n\004caca\030\001 \002(\005\022\022\n\005prova\030\002 \001(\0132\003.M2\"7\n\002M2\022" +
      "\017\n\002m1\030\001 \001(\0132\003.M1\022\017\n\002m3\030\002 \001(\0132\003.M3\022\017\n\002ok\030" +
      "\003 \001(\0132\003.M3B,\n!cat.ogasoft.protocolizer.m" +
      "essagesB\007provaaa"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_M1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_M1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M1_descriptor,
        new java.lang.String[] { "M3", });
    internal_static_M3_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_M3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M3_descriptor,
        new java.lang.String[] { "Caca", "Prova", });
    internal_static_M2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_M2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M2_descriptor,
        new java.lang.String[] { "M1", "M3", "Ok", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
