// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cat/ogasoft/protocolizer/protoc/prova2.proto

package cat.ogasoft.protocolizer.messages;

public final class prova2 {
  private prova2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface M1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2> 
        getLlistaList();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova2.M2 getLlista(int index);
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    int getLlistaCount();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    java.util.List<? extends cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder> 
        getLlistaOrBuilderList();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder getLlistaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code M1}
   */
  public  static final class M1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M1)
      M1OrBuilder {
    // Use M1.newBuilder() to construct.
    private M1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M1() {
      llista_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                llista_ = new java.util.ArrayList<cat.ogasoft.protocolizer.messages.prova2.M2>();
                mutable_bitField0_ |= 0x00000001;
              }
              llista_.add(
                  input.readMessage(cat.ogasoft.protocolizer.messages.prova2.M2.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          llista_ = java.util.Collections.unmodifiableList(llista_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.prova2.internal_static_M1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.prova2.internal_static_M1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.prova2.M1.class, cat.ogasoft.protocolizer.messages.prova2.M1.Builder.class);
    }

    public static final int LLISTA_FIELD_NUMBER = 1;
    private java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2> llista_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    public java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2> getLlistaList() {
      return llista_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    public java.util.List<? extends cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder> 
        getLlistaOrBuilderList() {
      return llista_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    public int getLlistaCount() {
      return llista_.size();
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova2.M2 getLlista(int index) {
      return llista_.get(index);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated .M2 llista = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder getLlistaOrBuilder(
        int index) {
      return llista_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLlistaCount(); i++) {
        if (!getLlista(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < llista_.size(); i++) {
        output.writeMessage(1, llista_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < llista_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, llista_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova2.M1)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.prova2.M1 other = (cat.ogasoft.protocolizer.messages.prova2.M1) obj;

      boolean result = true;
      result = result && getLlistaList()
          .equals(other.getLlistaList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLlistaCount() > 0) {
        hash = (37 * hash) + LLISTA_FIELD_NUMBER;
        hash = (53 * hash) + getLlistaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova2.M1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M1)
        cat.ogasoft.protocolizer.messages.prova2.M1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova2.M1.class, cat.ogasoft.protocolizer.messages.prova2.M1.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.prova2.M1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLlistaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (llistaBuilder_ == null) {
          llista_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          llistaBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M1_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.prova2.M1 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.prova2.M1.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.prova2.M1 build() {
        cat.ogasoft.protocolizer.messages.prova2.M1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.prova2.M1 buildPartial() {
        cat.ogasoft.protocolizer.messages.prova2.M1 result = new cat.ogasoft.protocolizer.messages.prova2.M1(this);
        int from_bitField0_ = bitField0_;
        if (llistaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            llista_ = java.util.Collections.unmodifiableList(llista_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.llista_ = llista_;
        } else {
          result.llista_ = llistaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.prova2.M1) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.prova2.M1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova2.M1 other) {
        if (other == cat.ogasoft.protocolizer.messages.prova2.M1.getDefaultInstance()) return this;
        if (llistaBuilder_ == null) {
          if (!other.llista_.isEmpty()) {
            if (llista_.isEmpty()) {
              llista_ = other.llista_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLlistaIsMutable();
              llista_.addAll(other.llista_);
            }
            onChanged();
          }
        } else {
          if (!other.llista_.isEmpty()) {
            if (llistaBuilder_.isEmpty()) {
              llistaBuilder_.dispose();
              llistaBuilder_ = null;
              llista_ = other.llista_;
              bitField0_ = (bitField0_ & ~0x00000001);
              llistaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLlistaFieldBuilder() : null;
            } else {
              llistaBuilder_.addAllMessages(other.llista_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLlistaCount(); i++) {
          if (!getLlista(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.prova2.M1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.prova2.M1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2> llista_ =
        java.util.Collections.emptyList();
      private void ensureLlistaIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          llista_ = new java.util.ArrayList<cat.ogasoft.protocolizer.messages.prova2.M2>(llista_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova2.M2, cat.ogasoft.protocolizer.messages.prova2.M2.Builder, cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder> llistaBuilder_;

      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2> getLlistaList() {
        if (llistaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(llista_);
        } else {
          return llistaBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public int getLlistaCount() {
        if (llistaBuilder_ == null) {
          return llista_.size();
        } else {
          return llistaBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova2.M2 getLlista(int index) {
        if (llistaBuilder_ == null) {
          return llista_.get(index);
        } else {
          return llistaBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder setLlista(
          int index, cat.ogasoft.protocolizer.messages.prova2.M2 value) {
        if (llistaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLlistaIsMutable();
          llista_.set(index, value);
          onChanged();
        } else {
          llistaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder setLlista(
          int index, cat.ogasoft.protocolizer.messages.prova2.M2.Builder builderForValue) {
        if (llistaBuilder_ == null) {
          ensureLlistaIsMutable();
          llista_.set(index, builderForValue.build());
          onChanged();
        } else {
          llistaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder addLlista(cat.ogasoft.protocolizer.messages.prova2.M2 value) {
        if (llistaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLlistaIsMutable();
          llista_.add(value);
          onChanged();
        } else {
          llistaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder addLlista(
          int index, cat.ogasoft.protocolizer.messages.prova2.M2 value) {
        if (llistaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLlistaIsMutable();
          llista_.add(index, value);
          onChanged();
        } else {
          llistaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder addLlista(
          cat.ogasoft.protocolizer.messages.prova2.M2.Builder builderForValue) {
        if (llistaBuilder_ == null) {
          ensureLlistaIsMutable();
          llista_.add(builderForValue.build());
          onChanged();
        } else {
          llistaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder addLlista(
          int index, cat.ogasoft.protocolizer.messages.prova2.M2.Builder builderForValue) {
        if (llistaBuilder_ == null) {
          ensureLlistaIsMutable();
          llista_.add(index, builderForValue.build());
          onChanged();
        } else {
          llistaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder addAllLlista(
          java.lang.Iterable<? extends cat.ogasoft.protocolizer.messages.prova2.M2> values) {
        if (llistaBuilder_ == null) {
          ensureLlistaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, llista_);
          onChanged();
        } else {
          llistaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder clearLlista() {
        if (llistaBuilder_ == null) {
          llista_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          llistaBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public Builder removeLlista(int index) {
        if (llistaBuilder_ == null) {
          ensureLlistaIsMutable();
          llista_.remove(index);
          onChanged();
        } else {
          llistaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova2.M2.Builder getLlistaBuilder(
          int index) {
        return getLlistaFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder getLlistaOrBuilder(
          int index) {
        if (llistaBuilder_ == null) {
          return llista_.get(index);  } else {
          return llistaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public java.util.List<? extends cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder> 
           getLlistaOrBuilderList() {
        if (llistaBuilder_ != null) {
          return llistaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(llista_);
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova2.M2.Builder addLlistaBuilder() {
        return getLlistaFieldBuilder().addBuilder(
            cat.ogasoft.protocolizer.messages.prova2.M2.getDefaultInstance());
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova2.M2.Builder addLlistaBuilder(
          int index) {
        return getLlistaFieldBuilder().addBuilder(
            index, cat.ogasoft.protocolizer.messages.prova2.M2.getDefaultInstance());
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated .M2 llista = 1;</code>
       */
      public java.util.List<cat.ogasoft.protocolizer.messages.prova2.M2.Builder> 
           getLlistaBuilderList() {
        return getLlistaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova2.M2, cat.ogasoft.protocolizer.messages.prova2.M2.Builder, cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder> 
          getLlistaFieldBuilder() {
        if (llistaBuilder_ == null) {
          llistaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.prova2.M2, cat.ogasoft.protocolizer.messages.prova2.M2.Builder, cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder>(
                  llista_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          llista_ = null;
        }
        return llistaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M1)
    }

    // @@protoc_insertion_point(class_scope:M1)
    private static final cat.ogasoft.protocolizer.messages.prova2.M1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova2.M1();
    }

    public static cat.ogasoft.protocolizer.messages.prova2.M1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M1>
        PARSER = new com.google.protobuf.AbstractParser<M1>() {
      public M1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M1> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.prova2.M1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface M2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    boolean hasCaca();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    int getCaca();
  }
  /**
   * Protobuf type {@code M2}
   */
  public  static final class M2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M2)
      M2OrBuilder {
    // Use M2.newBuilder() to construct.
    private M2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M2() {
      caca_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              caca_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.prova2.internal_static_M2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.prova2.internal_static_M2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.prova2.M2.class, cat.ogasoft.protocolizer.messages.prova2.M2.Builder.class);
    }

    private int bitField0_;
    public static final int CACA_FIELD_NUMBER = 1;
    private int caca_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    public boolean hasCaca() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>required int32 caca = 1;</code>
     */
    public int getCaca() {
      return caca_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCaca()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, caca_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, caca_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova2.M2)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.prova2.M2 other = (cat.ogasoft.protocolizer.messages.prova2.M2) obj;

      boolean result = true;
      result = result && (hasCaca() == other.hasCaca());
      if (hasCaca()) {
        result = result && (getCaca()
            == other.getCaca());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCaca()) {
        hash = (37 * hash) + CACA_FIELD_NUMBER;
        hash = (53 * hash) + getCaca();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova2.M2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova2.M2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M2)
        cat.ogasoft.protocolizer.messages.prova2.M2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova2.M2.class, cat.ogasoft.protocolizer.messages.prova2.M2.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.prova2.M2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        caca_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.prova2.internal_static_M2_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.prova2.M2 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.prova2.M2.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.prova2.M2 build() {
        cat.ogasoft.protocolizer.messages.prova2.M2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.prova2.M2 buildPartial() {
        cat.ogasoft.protocolizer.messages.prova2.M2 result = new cat.ogasoft.protocolizer.messages.prova2.M2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.caca_ = caca_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.prova2.M2) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.prova2.M2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova2.M2 other) {
        if (other == cat.ogasoft.protocolizer.messages.prova2.M2.getDefaultInstance()) return this;
        if (other.hasCaca()) {
          setCaca(other.getCaca());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCaca()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.prova2.M2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.prova2.M2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int caca_ ;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public boolean hasCaca() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public int getCaca() {
        return caca_;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public Builder setCaca(int value) {
        bitField0_ |= 0x00000001;
        caca_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>required int32 caca = 1;</code>
       */
      public Builder clearCaca() {
        bitField0_ = (bitField0_ & ~0x00000001);
        caca_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M2)
    }

    // @@protoc_insertion_point(class_scope:M2)
    private static final cat.ogasoft.protocolizer.messages.prova2.M2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova2.M2();
    }

    public static cat.ogasoft.protocolizer.messages.prova2.M2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M2>
        PARSER = new com.google.protobuf.AbstractParser<M2>() {
      public M2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M2> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.prova2.M2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,cat/ogasoft/protocolizer/protoc/prova2" +
      ".proto\"\031\n\002M1\022\023\n\006llista\030\001 \003(\0132\003.M2\"\022\n\002M2\022" +
      "\014\n\004caca\030\001 \002(\005B+\n!cat.ogasoft.protocolize" +
      "r.messagesB\006prova2"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_M1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_M1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M1_descriptor,
        new java.lang.String[] { "Llista", });
    internal_static_M2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_M2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M2_descriptor,
        new java.lang.String[] { "Caca", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
