// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cat/ogasoft/protocolizer/protoc/prova.proto

package cat.ogasoft.protocolizer.messages;

public final class prova {
  private prova() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface M1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    java.util.List<java.lang.Integer> getLlistaList();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    int getLlistaCount();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    int getLlista(int index);
  }
  /**
   * Protobuf type {@code M1}
   */
  public  static final class M1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M1)
      M1OrBuilder {
    // Use M1.newBuilder() to construct.
    private M1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M1() {
      llista_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                llista_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              llista_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                llista_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                llista_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          llista_ = java.util.Collections.unmodifiableList(llista_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.prova.internal_static_M1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.prova.internal_static_M1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.prova.M1.class, cat.ogasoft.protocolizer.messages.prova.M1.Builder.class);
    }

    public static final int LLISTA_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> llista_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getLlistaList() {
      return llista_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    public int getLlistaCount() {
      return llista_.size();
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>repeated int32 llista = 1;</code>
     */
    public int getLlista(int index) {
      return llista_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < llista_.size(); i++) {
        output.writeInt32(1, llista_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < llista_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(llista_.get(i));
        }
        size += dataSize;
        size += 1 * getLlistaList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova.M1)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.prova.M1 other = (cat.ogasoft.protocolizer.messages.prova.M1) obj;

      boolean result = true;
      result = result && getLlistaList()
          .equals(other.getLlistaList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLlistaCount() > 0) {
        hash = (37 * hash) + LLISTA_FIELD_NUMBER;
        hash = (53 * hash) + getLlistaList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova.M1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova.M1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M1)
        cat.ogasoft.protocolizer.messages.prova.M1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova.internal_static_M1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova.internal_static_M1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova.M1.class, cat.ogasoft.protocolizer.messages.prova.M1.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.prova.M1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        llista_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.prova.internal_static_M1_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.prova.M1 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.prova.M1.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.prova.M1 build() {
        cat.ogasoft.protocolizer.messages.prova.M1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.prova.M1 buildPartial() {
        cat.ogasoft.protocolizer.messages.prova.M1 result = new cat.ogasoft.protocolizer.messages.prova.M1(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          llista_ = java.util.Collections.unmodifiableList(llista_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.llista_ = llista_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.prova.M1) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.prova.M1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova.M1 other) {
        if (other == cat.ogasoft.protocolizer.messages.prova.M1.getDefaultInstance()) return this;
        if (!other.llista_.isEmpty()) {
          if (llista_.isEmpty()) {
            llista_ = other.llista_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLlistaIsMutable();
            llista_.addAll(other.llista_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.prova.M1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.prova.M1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> llista_ = java.util.Collections.emptyList();
      private void ensureLlistaIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          llista_ = new java.util.ArrayList<java.lang.Integer>(llista_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getLlistaList() {
        return java.util.Collections.unmodifiableList(llista_);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public int getLlistaCount() {
        return llista_.size();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public int getLlista(int index) {
        return llista_.get(index);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public Builder setLlista(
          int index, int value) {
        ensureLlistaIsMutable();
        llista_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public Builder addLlista(int value) {
        ensureLlistaIsMutable();
        llista_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public Builder addAllLlista(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLlistaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, llista_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>repeated int32 llista = 1;</code>
       */
      public Builder clearLlista() {
        llista_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M1)
    }

    // @@protoc_insertion_point(class_scope:M1)
    private static final cat.ogasoft.protocolizer.messages.prova.M1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova.M1();
    }

    public static cat.ogasoft.protocolizer.messages.prova.M1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M1>
        PARSER = new com.google.protobuf.AbstractParser<M1>() {
      public M1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M1> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.prova.M1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+cat/ogasoft/protocolizer/protoc/prova." +
      "proto\"\024\n\002M1\022\016\n\006llista\030\001 \003(\005B*\n!cat.ogaso" +
      "ft.protocolizer.messagesB\005prova"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_M1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_M1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M1_descriptor,
        new java.lang.String[] { "Llista", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
