// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prova6.proto

package cat.ogasoft.protocolizer.messages;

public final class prova6 {
  private prova6() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface M1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:M1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    boolean hasM1();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova6.M1.M2 getM1();
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder getM1OrBuilder();
  }
  /**
   * Protobuf type {@code M1}
   */
  public  static final class M1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:M1)
      M1OrBuilder {
    // Use M1.newBuilder() to construct.
    private M1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private M1() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private M1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = m1_.toBuilder();
              }
              m1_ = input.readMessage(cat.ogasoft.protocolizer.messages.prova6.M1.M2.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m1_);
                m1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cat.ogasoft.protocolizer.messages.prova6.M1.class, cat.ogasoft.protocolizer.messages.prova6.M1.Builder.class);
    }

    public interface M2OrBuilder extends
        // @@protoc_insertion_point(interface_extends:M1.M2)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 c = 1;</code>
       */
      boolean hasC();
      /**
       * <code>required int32 c = 1;</code>
       */
      int getC();
    }
    /**
     * Protobuf type {@code M1.M2}
     */
    public  static final class M2 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:M1.M2)
        M2OrBuilder {
      // Use M2.newBuilder() to construct.
      private M2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private M2() {
        c_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private M2(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                c_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_M2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_M2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova6.M1.M2.class, cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder.class);
      }

      private int bitField0_;
      public static final int C_FIELD_NUMBER = 1;
      private int c_;
      /**
       * <code>required int32 c = 1;</code>
       */
      public boolean hasC() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 c = 1;</code>
       */
      public int getC() {
        return c_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasC()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, c_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, c_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova6.M1.M2)) {
          return super.equals(obj);
        }
        cat.ogasoft.protocolizer.messages.prova6.M1.M2 other = (cat.ogasoft.protocolizer.messages.prova6.M1.M2) obj;

        boolean result = true;
        result = result && (hasC() == other.hasC());
        if (hasC()) {
          result = result && (getC()
              == other.getC());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasC()) {
          hash = (37 * hash) + C_FIELD_NUMBER;
          hash = (53 * hash) + getC();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova6.M1.M2 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code M1.M2}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:M1.M2)
          cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_M2_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_M2_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cat.ogasoft.protocolizer.messages.prova6.M1.M2.class, cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder.class);
        }

        // Construct using cat.ogasoft.protocolizer.messages.prova6.M1.M2.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          c_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_M2_descriptor;
        }

        public cat.ogasoft.protocolizer.messages.prova6.M1.M2 getDefaultInstanceForType() {
          return cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance();
        }

        public cat.ogasoft.protocolizer.messages.prova6.M1.M2 build() {
          cat.ogasoft.protocolizer.messages.prova6.M1.M2 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cat.ogasoft.protocolizer.messages.prova6.M1.M2 buildPartial() {
          cat.ogasoft.protocolizer.messages.prova6.M1.M2 result = new cat.ogasoft.protocolizer.messages.prova6.M1.M2(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.c_ = c_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cat.ogasoft.protocolizer.messages.prova6.M1.M2) {
            return mergeFrom((cat.ogasoft.protocolizer.messages.prova6.M1.M2)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova6.M1.M2 other) {
          if (other == cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance()) return this;
          if (other.hasC()) {
            setC(other.getC());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasC()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cat.ogasoft.protocolizer.messages.prova6.M1.M2 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cat.ogasoft.protocolizer.messages.prova6.M1.M2) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int c_ ;
        /**
         * <code>required int32 c = 1;</code>
         */
        public boolean hasC() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 c = 1;</code>
         */
        public int getC() {
          return c_;
        }
        /**
         * <code>required int32 c = 1;</code>
         */
        public Builder setC(int value) {
          bitField0_ |= 0x00000001;
          c_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 c = 1;</code>
         */
        public Builder clearC() {
          bitField0_ = (bitField0_ & ~0x00000001);
          c_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:M1.M2)
      }

      // @@protoc_insertion_point(class_scope:M1.M2)
      private static final cat.ogasoft.protocolizer.messages.prova6.M1.M2 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova6.M1.M2();
      }

      public static cat.ogasoft.protocolizer.messages.prova6.M1.M2 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<M2>
          PARSER = new com.google.protobuf.AbstractParser<M2>() {
        public M2 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new M2(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<M2> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<M2> getParserForType() {
        return PARSER;
      }

      public cat.ogasoft.protocolizer.messages.prova6.M1.M2 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int M1_FIELD_NUMBER = 1;
    private cat.ogasoft.protocolizer.messages.prova6.M1.M2 m1_;
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    public boolean hasM1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova6.M1.M2 getM1() {
      return m1_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance() : m1_;
    }
    /**
     * <pre>
     *prova
     * </pre>
     *
     * <code>optional .M1.M2 m1 = 1;</code>
     */
    public cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder getM1OrBuilder() {
      return m1_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance() : m1_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasM1()) {
        if (!getM1().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getM1());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getM1());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cat.ogasoft.protocolizer.messages.prova6.M1)) {
        return super.equals(obj);
      }
      cat.ogasoft.protocolizer.messages.prova6.M1 other = (cat.ogasoft.protocolizer.messages.prova6.M1) obj;

      boolean result = true;
      result = result && (hasM1() == other.hasM1());
      if (hasM1()) {
        result = result && getM1()
            .equals(other.getM1());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM1()) {
        hash = (37 * hash) + M1_FIELD_NUMBER;
        hash = (53 * hash) + getM1().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cat.ogasoft.protocolizer.messages.prova6.M1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cat.ogasoft.protocolizer.messages.prova6.M1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code M1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:M1)
        cat.ogasoft.protocolizer.messages.prova6.M1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cat.ogasoft.protocolizer.messages.prova6.M1.class, cat.ogasoft.protocolizer.messages.prova6.M1.Builder.class);
      }

      // Construct using cat.ogasoft.protocolizer.messages.prova6.M1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getM1FieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (m1Builder_ == null) {
          m1_ = null;
        } else {
          m1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cat.ogasoft.protocolizer.messages.prova6.internal_static_M1_descriptor;
      }

      public cat.ogasoft.protocolizer.messages.prova6.M1 getDefaultInstanceForType() {
        return cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance();
      }

      public cat.ogasoft.protocolizer.messages.prova6.M1 build() {
        cat.ogasoft.protocolizer.messages.prova6.M1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cat.ogasoft.protocolizer.messages.prova6.M1 buildPartial() {
        cat.ogasoft.protocolizer.messages.prova6.M1 result = new cat.ogasoft.protocolizer.messages.prova6.M1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (m1Builder_ == null) {
          result.m1_ = m1_;
        } else {
          result.m1_ = m1Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cat.ogasoft.protocolizer.messages.prova6.M1) {
          return mergeFrom((cat.ogasoft.protocolizer.messages.prova6.M1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cat.ogasoft.protocolizer.messages.prova6.M1 other) {
        if (other == cat.ogasoft.protocolizer.messages.prova6.M1.getDefaultInstance()) return this;
        if (other.hasM1()) {
          mergeM1(other.getM1());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasM1()) {
          if (!getM1().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cat.ogasoft.protocolizer.messages.prova6.M1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cat.ogasoft.protocolizer.messages.prova6.M1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private cat.ogasoft.protocolizer.messages.prova6.M1.M2 m1_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova6.M1.M2, cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder, cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder> m1Builder_;
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public boolean hasM1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1.M2 getM1() {
        if (m1Builder_ == null) {
          return m1_ == null ? cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance() : m1_;
        } else {
          return m1Builder_.getMessage();
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public Builder setM1(cat.ogasoft.protocolizer.messages.prova6.M1.M2 value) {
        if (m1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m1_ = value;
          onChanged();
        } else {
          m1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public Builder setM1(
          cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder builderForValue) {
        if (m1Builder_ == null) {
          m1_ = builderForValue.build();
          onChanged();
        } else {
          m1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public Builder mergeM1(cat.ogasoft.protocolizer.messages.prova6.M1.M2 value) {
        if (m1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              m1_ != null &&
              m1_ != cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance()) {
            m1_ =
              cat.ogasoft.protocolizer.messages.prova6.M1.M2.newBuilder(m1_).mergeFrom(value).buildPartial();
          } else {
            m1_ = value;
          }
          onChanged();
        } else {
          m1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public Builder clearM1() {
        if (m1Builder_ == null) {
          m1_ = null;
          onChanged();
        } else {
          m1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder getM1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getM1FieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      public cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder getM1OrBuilder() {
        if (m1Builder_ != null) {
          return m1Builder_.getMessageOrBuilder();
        } else {
          return m1_ == null ?
              cat.ogasoft.protocolizer.messages.prova6.M1.M2.getDefaultInstance() : m1_;
        }
      }
      /**
       * <pre>
       *prova
       * </pre>
       *
       * <code>optional .M1.M2 m1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cat.ogasoft.protocolizer.messages.prova6.M1.M2, cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder, cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder> 
          getM1FieldBuilder() {
        if (m1Builder_ == null) {
          m1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cat.ogasoft.protocolizer.messages.prova6.M1.M2, cat.ogasoft.protocolizer.messages.prova6.M1.M2.Builder, cat.ogasoft.protocolizer.messages.prova6.M1.M2OrBuilder>(
                  getM1(),
                  getParentForChildren(),
                  isClean());
          m1_ = null;
        }
        return m1Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:M1)
    }

    // @@protoc_insertion_point(class_scope:M1)
    private static final cat.ogasoft.protocolizer.messages.prova6.M1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cat.ogasoft.protocolizer.messages.prova6.M1();
    }

    public static cat.ogasoft.protocolizer.messages.prova6.M1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<M1>
        PARSER = new com.google.protobuf.AbstractParser<M1>() {
      public M1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new M1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<M1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<M1> getParserForType() {
      return PARSER;
    }

    public cat.ogasoft.protocolizer.messages.prova6.M1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_M1_M2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_M1_M2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014prova6.proto\")\n\002M1\022\022\n\002m1\030\001 \001(\0132\006.M1.M2" +
      "\032\017\n\002M2\022\t\n\001c\030\001 \002(\005B+\n!cat.ogasoft.protoco" +
      "lizer.messagesB\006prova6"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_M1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_M1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M1_descriptor,
        new java.lang.String[] { "M1", });
    internal_static_M1_M2_descriptor =
      internal_static_M1_descriptor.getNestedTypes().get(0);
    internal_static_M1_M2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_M1_M2_descriptor,
        new java.lang.String[] { "C", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
